### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by igorlend** [saper150/vscode-nginx-format#1]
What keyboard shortcut to format, I can not figure it out. Or just not working

**Comment by saper150** [comment]
Default shortcut for formatting is shift+alt+f, or you can right click an choose Format Document. And make sure that you also have https://marketplace.visualstudio.com/items?itemName=william-voyek.vscode-nginx this extension installed. When i was developing this extension i had the other extension installed and i didn't realized that it is required for my extension to run
